### ISSUE TITLE
Provider error

### ISSUE THREAD

**Issue by illiashvedov** [natintosh/intl_phone_number_input#39]
Hi, I caught this problem when choosing a country.

```
E/flutter ( 5902): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'owner' was called on null.
E/flutter ( 5902): Receiver: null
E/flutter ( 5902): Tried calling: owner
E/flutter ( 5902): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 5902): #1      Provider.of 
package:provider/src/provider.dart:193
E/flutter ( 5902): #2      _InputWidgetState._phoneNumberControllerListener 
package:intl_phone_number_input/…/widgets/input_widget.dart:290
E/flutter ( 5902): #3      _InputWidgetState.build.<anonymous closure> 
package:intl_phone_number_input/…/widgets/input_widget.dart:415
E/flutter ( 5902): <asynchronous suspension>
E/flutter ( 5902): #4      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:706
E/flutter ( 5902): #5      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:789
E/flutter ( 5902): #6      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter ( 5902): #7      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:486
E/flutter ( 5902): #8      BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:264
E/flutter ( 5902): #9      BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:236
E/flutter ( 5902): #10     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter ( 5902): #11     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
E/flutter ( 5902): #12     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter ( 5902): #13     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter ( 5902): #14     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter ( 5902): #15     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter ( 5902): #16     _rootRunUnary  (dart:async/zone.dart:1138:13)
E/flutter ( 5902): #17     _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
E/flutter ( 5902): #18     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
E/flutter ( 5902): #19     _invoke1  (dart:ui/hooks.dart:273:10)
E/flutter ( 5902): #20     _dispatchPointerDataPacket  (dart:ui/hooks.dart:182:5)
E/flutter ( 5902):
```

**Comment by natintosh** [comment]
It seems context was null when you choose a new country, I'll try to work on a fix for this.

**Comment by natintosh** [comment]
@illiashvedov I just published what I hope would be a fix to this

**Comment by natintosh** [comment]
Please lemme know this update fixes this issue before I close this. Thanks

**Comment by illiashvedov** [comment]
Hi, I tried now I do not have a provider error but the country does not change, I do not exclude that this is my local problem, possibly due to some other dependencies

**Comment by natintosh** [comment]
Thanks for the feedback @illiashvedov, I'll be closing this.

**Comment by codepushr** [comment]
Still having this issue:
```
NoSuchMethodError: The getter 'owner' was called on null.
Receiver: null
Tried calling: owner
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Provider.of (package:provider/src/provider.dart:193:15)
#2      _InputWidgetState._loadCountries (package:intl_phone_number_input/src/widgets/input_widget.dart:278:39)
#3      _InputWidgetState.initState.<anonymous closure> (package:intl_phone_number_input/src/widgets/input_widget.dart:362:41)
#4      new Future.delayed.<anonymous closure> (dart:async/future.dart:318:39)
#5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

I'm on version `^0.4.0+2`.

This is my setup with just 1 country:
```dart
InternationalPhoneNumberInput(
  onInputChanged: (PhoneNumber number) {
    print(number.phoneNumber);
  },
  onInputValidated: (bool value) {
    print(value);
  },
  textStyle: TextStyle(
    fontSize: 16,
  ),
  countries: ["AT"],
  ignoreBlank: false,
  autoValidate: false,
  initialValue: _number,
  inputBorder: InputBorder.none,
  textFieldController: phoneInputController,
),
```

**Comment by natintosh** [comment]
It seems this has to do with Provider, I guess I'll have to replace it with
